# Netlify configuration file

[build]
  # Serve the repository root
  publish = "."

[functions]
  # Serverless functions directory
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
