[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# If (and only if) your functions are NOT in "netlify/functions",
# uncomment one of these and set the correct path:
# [functions]
#   directory = "netlify/functions"
# or:
# [build]
#   functions = "netlify/functions"

# SPA routing so deep links don’t 404:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
