# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  # Serverless functions directory
  directory = "netlify/functions"

# SPA routing: send all paths to index.html so client-side router can handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
