name: Build (Vite + React)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload dist artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
